import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Navbar } from '@/components/Navbar/Navbar';
import { Footer } from '@/components/Footer/Footer';
import AnimatedCursor from 'react-animated-cursor';
import './globals.css';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' className='scroll-smooth'>
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<AnimatedCursor
					innerSize={12}
					outerSize={35}
					innerScale={1}
					outerScale={1.5}
					outerAlpha={0}
					innerStyle={{
						backgroundColor: '#ffff'
					}}
					outerStyle={{
						border: '2px solid #a1a1a1'
					}}
				/>
				<Navbar />
					{children}
				<Footer />
			</body>
		</html>
	);
}
